# Generated by Django 5.1 on 2025-05-11 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='license',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
