# Generated by Django 5.1 on 2025-05-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='license',
            field=models.CharField(editable=False, max_length=19, unique=True),
        ),
    ]
