# Generated by Django 5.1 on 2025-05-11 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='real_license',
            field=models.CharField(default=1, editable=False, max_length=19, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='license',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
