# Generated by Django 5.1 on 2025-05-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_real_license_alter_profile_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='license_active',
            field=models.BooleanField(default=False),
        ),
    ]
